---
- name: Install and Configure Kibana 7.1.x
  hosts: kibana
  become: yes
  vars:
    elk_version: "7.1.1"
    kibana_ports:
      - 5601   # Kibana 포트
    elasticsearch_host: "http://192.168.1.172:9200"  # Elasticsearch 서버 주소

  tasks:
    - name: Import Elastic GPG Key
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Add Kibana Repository
      yum_repository:
        name: kibana
        description: Kibana repository for 7.1.x
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        enabled: yes

    - name: Install Kibana
      yum:
        name: "kibana-{{ elk_version }}"
        state: present

    - name: Create Kibana log directory
      file:
        path: /var/log/kibana
        state: directory
        owner: kibana
        group: kibana
        mode: '0755'

    - name: Create Kibana log file
      file:
        path: /var/log/kibana/kibana.log
        state: touch
        owner: kibana
        group: kibana
        mode: '0664'

    - name: Configure Kibana settings
      copy:
        dest: /etc/kibana/kibana.yml
        content: |
          server.port: 5601
          server.host: "0.0.0.0"
          elasticsearch.hosts: ["{{ elasticsearch_host }}"]
          logging.dest: /var/log/kibana/kibana.log
          logging.verbose: true
        mode: '0644'
      notify: Restart Kibana

    - name: Enable and Start Kibana Service
      systemd:
        name: kibana
        enabled: yes
        state: started

    - name: Configure Firewall for Kibana
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      loop: "{{ kibana_ports }}"

    - name: Reload Firewalld
      command: firewall-cmd --reload

  handlers:
    - name: Restart Kibana
      systemd:
        name: kibana
        state: restarted
