name: Deploy ELK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

        - name: Debug: Check Repository Files
          run: ls -lR


      - name: Install Ansible
        run: |
          sudo yum install -y epel-release
          sudo yum install -y ansible

      - name: Run Ansible Playbook (Elasticsearch)
        run: ansible-playbook -i inventory.ini elasticsearch.yml

      - name: Run Ansible Playbook (Logstash)
        run: ansible-playbook -i i.github/workflows/inventory.ini logstash.yml

      - name: Run Ansible Playbook (Kibana)
        run: ansible-playbook -i inventory.ini kibana.yml
