name: Deploy ELK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible (if not installed)
        run: |
          if ! command -v ansible &> /dev/null; then
            sudo yum install -y epel-release
            sudo yum install -y ansible
          else
            echo "Ansible is already installed"
          fi

      - name: Add SSH key to known_hosts (Elasticsearch, Logstash, Kibana)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 192.168.1.172 >> ~/.ssh/known_hosts
          ssh-keyscan -H 192.168.1.173 >> ~/.ssh/known_hosts
          ssh-keyscan -H 192.168.1.176 >> ~/.ssh/known_hosts
        shell: bash

      - name: Run Ansible Playbook (Elasticsearch)
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i .github/workflows/inventory.ini playbook/elasticsearch.yml

      - name: Run Ansible Playbook (Logstash)
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i .github/workflows/inventory.ini playbook/logstash.yml

      - name: Run Ansible Playbook (Kibana)
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i .github/workflows/inventory.ini playbook/kibana.yml -vv
