name: Deploy ELK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo yum install -y epel-release
          sudo yum install -y ansible

      - name: Run Ansible Playbook (Elasticsearch)
        run: ansible-playbook -i inventory.ini playbooks/elasticsearch.yml

      - name: Run Ansible Playbook (Logstash)
        run: ansible-playbook -i inventory.ini playbooks/logstash.yml

      - name: Run Ansible Playbook (Kibana)
        run: ansible-playbook -i inventory.ini playbooks/kibana.yml
