name: Deploy ELK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible (if not installed)
        run: |
          if ! command -v ansible &> /dev/null; then
            sudo yum install -y epel-release
            sudo yum install -y ansible
          else
            echo "Ansible is already installed"
          fi

      - name: Run Ansible Playbook (Elasticsearch)
        run: |
          
          ansible-playbook -i .github/workflows/inventory.ini playbook/elasticsearch.yml -b


      - name: Run Ansible Playbook (Logstash)
        run: |
          set -e
           ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i .github/workflows/inventory.ini playbook/logstash.yml -b
          
      - name: Run Ansible Playbook (Kibana)
        run: |
          set -e
          ansible-playbook -i .github/workflows/inventory.ini playbook/kibana.yml -b
